### ISSUE TITLE
How to build Documentation

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/OSM-Bike-Ottawa-Tagging-Guide#23]
@heatshear I've included a document how to build the YAML based schema documentation.

https://github.com/osmottawa/OSM-Bike-Ottawa-Tagging-Guide/blob/master/README-build-docs.md

Let me know if you have any issues building the documentation, also let me know if building the YAML schema approach is easier (I think so...).

# OSM Bike Ottawa Tagging Guide

### Install

- [ ] Install the LTS or current version of [NodeJS](https://nodejs.org/en/).
- [ ] Clone/Download Repo to local computer via **Clone with SSH** or **Download Zip**.
- [ ] Install library's dependencies using `npm install`.
- [ ] Build docs via `npm run docs`.

### Install via CLI

```bash
$ git clone git@github.com:osmottawa/OSM-Bike-Ottawa-Tagging-Guide.git
$ cd OSM-Bike-Ottawa-Tagging-Guide
$ npm install
$ npm run docs
```

**Comment by rqode** [comment]
@DenisCarriere Github does not allow definitions of CI/CD pipelines for doing this type of things? I'm not too familiar with Github, but I believe Gitlab would allow you to do something like this.

**Comment by DenisCarriere** [comment]
CI/CD pipelines? You mean [TravisCI](https://travis-ci.org/)? There's tons more that have GitHub integration.

👎 Not switching to Gitlab

**Comment by rqode** [comment]
TravisCI would probably be OK, yes. The tricky part will be getting the generated documents committed and pushed.

**Comment by DenisCarriere** [comment]
@rqode It's working now.

🤦‍♂️ Unfortunately I lost the Git history 🤔 ... silly automated bots, always doing things  their not suppose to.

Seems to work now, no need to build the `README.md` document.

**Comment by rqode** [comment]
Great!
