### ISSUE TITLE
I can't figure out how to re-order the categories

### ISSUE THREAD

**Issue by heatshear** [osmottawa/OSM-Bike-Ottawa-Tagging-Guide#34]
I've been editing the readme... index and also contents, trying to put them into a logical order. But, it keeps reverting. I don't know what to do.

**Comment by heatshear** [comment]
think I maybe found the solution in documentation

**Comment by DenisCarriere** [comment]
👍 Yep you need to edit the YAML files now since every new commit will re-build the README.md

**Comment by DenisCarriere** [comment]
`documentation.yml` + `schema/*.yml` files
