### ISSUE TITLE
Bug; Remove reference to using Google imagery

### ISSUE THREAD

**Issue by govvin** [osmottawa/OSM-Bike-Ottawa-Tagging-Guide#43]
This is an excellent guideline! Thank you for sharing.

The only issue (2020-11-29, while I write this ticket), and this is important, is that you are encouraging people to refer to Google Streetview which is disallowed in OpenStreetMap.

![screenshot, JOSM Tips and Tricks, 2020-11-29](https://user-images.githubusercontent.com/5821688/100531159-b9652080-3235-11eb-8389-702b9b783578.png)

The Google Maps/Google Earth (including Streetview) [Terms of Service](https://www.google.com/help/terms_maps/) disallows users from using their imagery and data for creating or augmenting any mapping-related dataset. I'll quote the relevant section below:  
  > When using Google Maps/Google Earth, you may not […] use Google Maps/Google Earth to create or augment any other mapping-related dataset (including a mapping or navigation dataset, business listings database, mailing list or telemarketing list)

Checkout the [OpenStreeMap FAQ](https://wiki.openstreetmap.org/wiki/FAQ) for more information, or refer to [What images and maps may I use to make maps from?](https://wiki.openstreetmap.org/wiki/FAQ#What_images_and_maps_may_I_use_to_make_maps_from.3F) for details.

**Comment by shawngettler** [comment]
Issue resolved by removing reference to Streetview. Thanks, @govvin .
