### ISSUE TITLE
cycleway:buffer width in meters

### ISSUE THREAD

**Issue by kaligrafy** [osmottawa/OSM-Bike-Ottawa-Tagging-Guide#48]
Hi! We are currently tagging cycling paths in the Montreal area and we use a width in meters for the cycleway:buffer tag.
In your guide, you tell users it should be a yes/no value instead, but the openstreetmap wiki suggest it would be better to use the actual width. Do you accept both yes or a float for the buffer width in meter?

**Comment by YaroShkvorets** [comment]
Yeah good idea. I'll change it.

**Comment by kaligrafy** [comment]
Thanks!
